language: ruby
rvm:
- 2.1

before_script:
- openssl aes-256-cbc -K $encrypted_76a5fcdd1b69_key -iv $encrypted_76a5fcdd1b69_iv -in deploy_key.enc -out deploy_key -d
- chmod go-rwx .travisdeploykey
- eval `ssh-agent -s`
- ssh-add .travisdeploykey
- git config user.name "Travis-CI"
- git config user.email "noreply@travis-ci.org"
- COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from `git log -n 1 --format='commit %h - %s'`"
script:
- rake cibuild
- set -e
- rake build
- git checkout -b gh-pages
- echo "ecox.rocks" > _site/CNAME
- git add -f _site/
- 'git commit -m "${COMMIT_MESSAGE}"'
- git filter-branch -f --subdirectory-filter _site/
- git push -f git@github.com:erikcox/erikcox.github.io.git gh-pages:gh-pages

branches:
  only:
    - master

env:
- NOKOGIRI_USE_SYSTEM_LIBRARIES=true
