title: Erik Cox
description: My Personal Website
author: Erik Cox
logo: https://i.imgur.com/XwHr5HA.jpg
github: https://github.com/erikcox
about: Freelance developer

baseurl:
url: https://ecox.rocks

disqus_shortname: erikcox
google_analytics: UA-61053689-1

share:
  twitter_username: erikerik
  fb_appid: 1512247512400912

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
